name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Build
        run: |
          npm install
          npm run build

      - name: Package
        run: |
          PLUGIN_NAME=$(basename "$GITHUB_REPOSITORY")
          mkdir "$PLUGIN_NAME"
          cp main.js manifest.json styles.css README.md "$PLUGIN_NAME"
          zip -r "$PLUGIN_NAME.zip" "$PLUGIN_NAME"

      - name: Ensure release exists and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          if ! gh release view "$tag" &>/dev/null; then
            gh release create "$tag" \
              --title="$tag" \
              --draft \
              main.js manifest.json styles.css
          fi

          gh release upload "$tag" main.js manifest.json styles.css "${{ github.event.repository.name }}.zip" --clobber
